
name: Release

# Controls when the action will run
on:
  push:
    branches: 
      - 'develop'
env:
  release_name: 'Release_IC'

jobs:
  job1:
    name: Merge
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'RELEASE') }}
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout de repositorio
        uses: actions/checkout@v2
      - name: Crear rama release
        run: |
          git checkout -b release
          git push -f -u origin release
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g @angular/cli @angular/compiler-cli typescript
      - run: npm install --force
      - run: npm install -g @angular/cli@12.1.2
      - run: npm install @angular/animations
      - run: ng test --browsers ChromeHeadless --watch=false
  job2:
    name: Mezcla_Main
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Mezcla rama1 -> rama2
        uses: tukasz/direct-merge-action@master 
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: release
          target-branch: main
